# Generated by Django 5.0.6 on 2024-05-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
